kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.ReplicaNumber }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
    volumes:
        - name: index-html
          configMap:
            name: '{{ .Chart.Name }}-html'
            defaultMode: 420
      containers:
      - resources: {}
        terminationMessagePath: /dev/termination-log
        name: {{ .Chart.Name }}
        ports:
        - containerPort: {{ .Values.containers.containerPort }}
          protocol: TCP
        imagePullPolicy: Always
        terminationMessagePolicy: File
        image: "quay.io/<myuser15/repo:v1"
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        volumeMounts:
        - name: index-html
          mountPath: /tmp/html
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 25%
    maxSurge: 25%
revisionHistoryLimit: 10

  